
version: '3'
services:
  backend:
    build:
      context: ./medical-assistance
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin@admin.com
      - POSTGRES_DB=assistance_medicine
      - POSTGRES_PASSWORD=12345
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./Client/miapp.conf:/etc/nginx/conf.d/default.conf:ro
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=assistance_medicine
      - POSTGRES_USER=postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8888:80
    depends_on:
      - database